
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-devx-myapp
  name: myapp
  namespace: devx
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-devx-myapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-devx-myapp
    spec:
      containers:
      - image: ajaysheoran2323/mynewimage:$BUILD_NUMBER
        imagePullPolicy: Always
        name: myapp
        ports:
        - containerPort: 80
          name: 80tcp803
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
